import {
  faAddressCard,
  faAngleRight,
  faAngleUp,
  faAppleWhole,
  faArrowRightFromBracket,
  faBacon,
  faBowlFood,
  faBowlRice,
  faBurger,
  faCakeCandles,
  faCheck,
  faCircle,
  faCircleDot,
  faCirclePlus,
  faClock,
  faClover,
  faCookieBite,
  faDrumstickBite,
  faEdit,
  faEye,
  faEyeSlash,
  faFishFins,
  faHouse,
  faLock,
  faMagnifyingGlass,
  faMartiniGlass,
  faPlus,
  faSeedling,
  faTrashCan,
  faUser,
  faUserGroup,
  faUtensils,
  faX,
} from "@fortawesome/free-solid-svg-icons";

import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";

export const icons: Record<string, IconDefinition> = {
  home: faHouse,
  user: faUser,
  userName: faAddressCard,
  eyeSlash: faEyeSlash,
  eye: faEye,
  lock: faLock,
  logout: faArrowRightFromBracket,

  dot: faCircle,
  clock: faClock,
  userGroup: faUserGroup,
  check: faCheck,
  cancel: faX,

  search: faMagnifyingGlass,
  edit: faEdit,
  plus: faPlus,
  add: faCirclePlus,
  delete: faTrashCan,

  angleRight: faAngleRight,
  angleUp: faAngleUp,
  cake: faCakeCandles,
  beef: faBacon,
  chicken: faDrumstickBite,
  fish: faFishFins,
  salad: faClover,
  soup: faBowlFood,
  pasta: faUtensils,
  drink: faMartiniGlass,
  dessert: faCookieBite,
  burger: faBurger,
  plate: faBowlRice,
  light: faAppleWhole,
  healthyFood: faSeedling,
};
